version: '3.9'

services:
  api:
    container_name: personal-registration
    image: martinholutero1/personal-registration:${DOCKER_IMAGE_TAG}
    # build:
    #   context: .
    #   dockerfile: .docker/Dockerfile.api
    env_file:
      .env
    networks:
      - personal-registration-network
    depends_on:
      - database
    ports:
      - "8000:3001"

  database:
    container_name: personal-registration-postgres-database
    image: postgres:11
    environment:
      POSTGRES_USER: personal_registration
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: personal_registration
    ports:
      - "5432:5432"
    networks:
      - personal-registration-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/connection/:/docker-entrypoint-initdb.d/

networks:
  personal-registration-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
